server:
  port: 0

licenseUrl: classpath:license.xml

security:
  enabled: false
  oauth2:
    client:
      clientId:
      clientSecret:
      scope:
      accessTokenUri:
      userAuthorizationUri:
    resource:
      jwt:
        key-uri:

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: ru.diasoft.micro.lib.config.H2PhysicalNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath*:liquibase-extracted/rootChangeLog.xml

dstrace:
  enabled: false

dslogging:
  nesting-level-limit: 2
  items-on-level-limit: 100
  exclude-items:
  include-items:

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    ru.diasoft.micro: DEBUG
    org.hibernate.type: INFO

