server:
  port: 8088
logging:
  config: classpath:log4j2.xml
springfox:
  documentation:
    swagger:
      v2:
        path=/swagger.json
spring:
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_CONSUMER_SERVER:localhost:9092}
      group-id: rest-service
    producer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_SERVER:localhost:9092}