server:
  port: 8761
spring:
  application:
    name: skyhunter-eureka-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
logging:
  level:
    com:
      netflix:
        eureka: ON
      discovery: ON
spec:
  replicas: 1
