server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    com:
      netflix:
        eureka: ON
      discovery: ON
spec:
  replicas: 1
